config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :films, only: [:index, :edit, :update]

  root to: 'films#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user

  scope :for_team, ->(team) { where(user_id: team.users.map(&:id)) }
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  default_form_builder FilmFormBuilder


  protect_from_forgery with: :exception, prepend: true
  before_action :authenticate_user!

  # after_action :verify_authorized
  # after_action :verify_policy_scoped

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  private
  def user_not_authorized(exception, redirect_path = nil)
    policy_name = exception.policy.class.to_s.underscore

    flash[:alert] = "translation for 'pundit.#{policy_name}.#{exception.query}' goes here"
    redirect_to(redirect_path || request.referrer || root_path)
  end


end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    authorize Film
    @films = policy_scope(Film)
  end

  def edit
    @film = policy_scope(Film).find(params[:id])
    authorize @film
  end

  def update
    @film = policy_scope(Film).find(params[:id])
    @film.update(film_params)
    flash[:alert] = 'Film updated'
    redirect_to films_path
  end

  private
  def film_params
    params.require(:film).permit(:title, :tagline)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def html_title
    default = t('shared.page-title.suffix')
    return default unless content_for?(:page_title)

    "#{content_for(:page_title)} - #{default}".html_safe
  end
end

app/helpers/films_controller_helper.rb
module FilmsControllerHelper
end

app/views/films/edit.html.erb
<h1>Edit Film <%= @film.title %></h1>


<%= form_for @film do |f| %>
  <%= f.text_field :title, label: 'Film title' %>

  <%= f.text_field :tagline  %>

  <p />
  <%= f.submit 'Update film' %>

<% end %>

app/views/films/index.html.erb
<h1>Films and their taglines</h1>


<table>
  <tr>
    <th>Film</th>
    <th>Tagline</th>
    <th>User</th>
    <th>Team</th>
  </tr>
  <% @films.each do |film| %>
    <tr>
      <td><%= link_to film.title, edit_film_path(film) %></td>
      <td><%= film.tagline %></td>
      <td><%= film.user.name %></td>
      <td><%= film.user.team.name %></td>
    </tr>
  <% end %>
</table>

</p>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/layouts/_footer.html.erb
<footer class="govuk-footer " role="contentinfo">
  <div class="govuk-width-container ">
    <div class="govuk-footer__meta">
      <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">

        <h2 class="govuk-visually-hidden"><%= t('layouts.application.footer.support') %></h2>
        <ul class="govuk-footer__inline-list">
<!--          <li class="govuk-footer__inline-list-item">-->
            <%#= link_to t('layouts.application.footer.contact'), contact_path, class: 'govuk-footer__link' %>
<!--          </li>-->

          <li class="govuk-footer__inline-list-item">
            <a class="govuk-footer__link" href="#">
              <!-- TO DO add link -->
              <%= t('layouts.application.footer.feedback') %>
            </a>
          </li>

          <li class="govuk-footer__inline-list-item">
            <a class="govuk-footer__link" href="https://www.gov.uk/help/cookies">
              <%= t('layouts.application.footer.cookies') %>
            </a>
          </li>

          <li class="govuk-footer__inline-list-item">
            <a class="govuk-footer__link" href="https://www.gov.uk/government/publications/laa-online-portal-help-and-information">
              <!-- TO DO differs between provider/citizen -->
              <%= t('layouts.application.footer.terms') %>
            </a>
          </li>

          <li class="govuk-footer__inline-list-item">
            <a class="govuk-footer__link" href="https://mojdigital.blog.gov.uk/">
              <%= t('layouts.application.footer.digital_services') %>
            </a>
          </li>
        </ul>

        <svg role="presentation" focusable="false" class="govuk-footer__licence-logo" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 483.2 195.7" height="17" width="41">
          <path fill="currentColor" d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145" />
        </svg>
        <span class="govuk-footer__licence-description">
          <%= t('layouts.application.footer.span_text_1') %>
          <a class="govuk-footer__link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license"><%= t('layouts.application.footer.open_gov_link_text') %></a>,  <%= t('layouts.application.footer.span_text_2') %>
        </span>
      </div>
      <div class="govuk-footer__meta-item">
        <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© <%= t('layouts.application.footer.copyright') %></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="govuk-template">
<head>
  <title><%= html_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#0b0c0c" />

<!--  <link rel="shortcut icon" href="<%#= image_path('favicon.ico') %>" type="image/x-icon" />-->
  <link rel="mask-icon" href="/assets/images/govuk-mask-icon.svg" color="#0b0c0c" />
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/govuk-apple-touch-icon-180x180.png" />
  <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/govuk-apple-touch-icon-167x167.png" />
  <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/govuk-apple-touch-icon-152x152.png" />
  <link rel="apple-touch-icon" href="/assets/images/govuk-apple-touch-icon.png" />

  <!--[if !IE 8]> <link href="/govuk-frontend/all.css" rel="stylesheet"/> <![endif]-->

  <!--[if IE 8]> <link href="/govuk-frontend/all-ie8.css" rel="stylesheet" /> <![endif]-->

  <!--[if lt IE 9]> <script src="/html5-shiv/html5shiv.js"></script> <![endif]-->

  <meta property="og:image" content="/assets/images/govuk-opengraph-image.png" />
</head>

<body class="govuk-template__body ">
<script>
    document.body.className = (
        (document.body.className)
            ? document.body.className + ' js-enabled'
            : 'js-enabled'
    );
</script>

<a href="#main-content" class="govuk-skip-link">Skip to main content</a>

<%= render partial: 'layouts/header' %>

<div class="govuk-width-container">
  <div class="govuk-phase-banner">
    <p class="govuk-phase-banner__content">
      <strong class="govuk-tag govuk-phase-banner__content__tag ">
        Beta
      </strong>
      <span class="govuk-phase-banner__text">
            This is a new service – your
            <a class="govuk-link" href="#">feedback</a>
            will help us to improve it.
          </span>
    </p>
  </div>

  <%= content_for(:navigation) %>

  <main class="govuk-main-wrapper " id="main-content" role="main">
    <% if flash[:error] %>
      <div class="govuk-error-summary">
        <h2 class="govuk-error-summary__title"><%= flash[:error] %></h2>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class='govuk-warning-text'>
        <span class='govuk-warning-text__icon' aria-hidden='true'>i</span>
        <strong class='govuk-warning-text__text'>
          <span class='govuk-warning-text__assistive'>Notice</span>
          <%= flash[:notice] %>
        </strong>
      </div>
    <% end %>

    <%= yield %>
  </main>
</div>

<%= render partial: 'layouts/footer' %>

<script type='text/javascript'>
    window.GOVUKFrontend.initAll();
</script>
</body>
</html>